spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pizzeria?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: angarita93
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySql8Dialect

logging:
  level:
    org.springframework.security.web.*: debug



